CREATE TABLE VACUNA (
    CODIGO INTEGER NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DOSIS INTEGER NOT NULL,
    FABRICANTE VARCHAR(100) NOT NULL
);

INSERT INTO VACUNA (CODIGO, NOMBRE, DOSIS, FABRICANTE)
VALUES (1, 'Fiebre Amarilla', 1, 'Sanofi');

INSERT INTO VACUNA (CODIGO, NOMBRE, DOSIS, FABRICANTE)
VALUES (2, 'Hepatitis B', 3, 'Pfizer');


SELECT * FROM VACUNA